name: Em

on:
  schedule:
    -  workflow_dispatch:
      
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch results
        run: ./email.sh

      - name: Commit README.md
        run: |
          git config --local user.email "asn@example.com"
          git config --local user.name "
          git add res.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
