name: Fetch

on:
  schedule:
    - cron: "0 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22 * * *"
      
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch results
        run: date

      - name: Commit README.md
        run: |
          git config --local user.email "asn@example.com"
          git config --local user.name "ASN Bot"
          git add secs_ordered.txt
          git add secs.txt
          git add notifications.out
          git commit -m "Update results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
