name: Main

on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
      
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch results
        run: echo DONE >> README.md

      - name: Commit README.md
        run: |
          git config --local user.email "asn@example.com"
          git config --local user.name "ASN Bot"
          git add README.md
          git commit -m "Update results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
 
